//
// Created by anthony on 12/10/16.
//

#ifndef IRIS_CONSTANTS_H
#define IRIS_CONSTANTS_H
#define FILESYSTEM_PREFETCHER "FILESYSTEM_PREFETCHER"
#define OBJECTSTORE_PREFETCHER "OBJECTSTORE_PREFETCHER"
#endif //IRIS_CONSTANTS_H
