//
// Created by anthony on 12/10/16.
//

#ifndef IRIS_CONSTANTS_H
#define IRIS_CONSTANTS_H

#define FILESYSTEM_PREFETCHER "FILESYSTEM_PREFETCHER"
#define OBJECTSTORE_PREFETCHER "OBJECTSTORE_PREFETCHER"
#define IRIS_METADATA_MANAGER "IRIS_METADATA_MANAGER"
#define POSIX_METADATA_MANAGER "POSIX_METADATA_MANAGER"
#define MPIIO_METADATA_MANAGER "MPIIO_METADATA_MANAGER"
#define HDF5_METADATA_MANAGER "HDF5_METADATA_MANAGER"
#define PNETCDF_METADATA_MANAGER "PNETCDF_METADATA_MANAGER"
#define S3_METADATA_MANAGER "S3_METADATA_MANAGER"



#endif //IRIS_CONSTANTS_H
